### ISSUE TITLE
tidy up apache confs

### ISSUE THREAD

**Issue by JedMeister** [DocCyblade/tkl-odoo#19]
Apache site configs should be tidied up and consolidated.

Also @l-arnold I know that you are really keen on your tklwebcp page. I would really like to understand better what you use it for and why. TBH it doesn't really make a lot of sense to me but it's possible I'm missing something...

**Comment by JedMeister** [comment]
I am also inclined to remove the [apache status mod](https://github.com/DocCyblade/tkl-odoo/blob/dev/overlay/etc/apache2/mods-available/status.conf). It would be better to document that instead IMO.

Also I'm going to move the discussion of usage of a webcp to a new issue.

**Comment by l-arnold** [comment]
@JedMeister  Apologies from the start for a rather long response to what was a simple question.  The response goes in various directions.

The WebCp is basically a set of quick links to anything you might want to do with a TKL App.  It is not in Beta 4, but is in any of the builds from my side (you probably have one built).  To enable it just type "a2ensite odoo-12325.conf"  from Shell.

Once enabled both ports http:12325 and https:12324 are active with the CP.
Was modeled after what I recall being in the LAPP or Postgresql landing page (I think I just lifted and modified in fact).

Quick Buttons to
Webshell
Webmin
Odoo (or any other Ap)
Docs

Then "micro links" ala ConfConsole but hot, to a variety of other tools and places that can be interesting.

It is very nice not to be typing URL's all the time.  I actually get bruised fingers from typing too much and doing so for a repatitive URL is really a waste of energy.

The other part is that I really do use the Shell and Webmin systems quite intensively alongside the Main App.  I feel the DOC side is something that can grow, and it can also create a gateway to some shared WIKI situations as well (ala EtherPad).  It could also form a gateway to the TurnKey Universe if set up properly.

I spent a lot of time also making this system WORK.  It works behind a firewall and outside a firewall, it works with IP addresses and it works with DNS Host Names.  It is a really slick piece of work (IMHO).

Please give it a spin if you can.  If we can leave it "to be enabled" if some one wants it, that would work for me.  A lot of what I want in a system I want because I see the value for me working with it.  My "computer character" is mostly as a user and an implementer.  I do not consider myself truly a programmer but I can follow along and I can take on functional parts of systems to see what is working, what is not, what can be better and what to watch out for.

The console really is built from that perspective.

RELATED:  Be very careful with what you are doing with those CONF scripts.  They are working as Proxies for Odoo and they are forcing HTTPS for Odoo (but not for the Console just in case SSL problems were blocking full access to the APP).

Again, I did spend a lot of time on this element back in the summer and even though Jessie may be changing I would not just assume that all TKL systems are correct.  Witness my Magento Problems yesterday and today logged on the forums.

The Apache setup that we have is quite durable and has not been the source of any of our problems or debuging through this process.  I would not like to start having to focus on problems there now.

Changing Subject:
I am very concerned with TKLBAM as it was working on Wheezy for me the last 2 days in Magento.  I do think there can be some systematic approaches to debugging it.  It seems it may need a few more eyes on the situation.  There are a lot of settings that can get thrown out of focus.

Webmin Module still needs a fix there

Would be great to have a WebMin Project at TKL to put some various systems into place.  More precise "migrations and updates" rather than big TKLBAM restores.  Resetting of Passwords, Audits of Machines,  Security and Intrusion scans etc could all be implemented.

All good.  Just make the Apache Proxy work.  If you can keep the webcp.conf file intact so folks can call it  (or better if you keep it in, I think it is a gateway for development at TKL).  Main thing is getting Odoo put to bed and working a path for my "bigger build" to be brought in.  (File size as far as I can see is almost identical anyway)

I am not being selfish (even if I am).  I am trying to have a truly TurnKey Odoo system that ROCKS.  I think it can be a big STAR on the TKL Banner.  As we have seen, this is not an easy project.  

My Next one to go after may have to be Magento.  Documentation, at the very least, is needed.  I think some control points would also be helpful...  but those are other subjects.

**Comment by JedMeister** [comment]
webcp comment on issue #21 

Re TKLBAM, I answered your post on the forums. Did you get an email notification?

**Comment by l-arnold** [comment]
Saw an answer on the forums.  Not sure I recieved an email from there however.  Will look.

My post was after that.  Parrallel with your post I ran "turnkey-init" which both "fixed: and "unfixed" several issues at the same time.  (put it to sleep after that)

I will check again if there is another post there.

**Comment by l-arnold** [comment]
I need to catch up.  Is there a new Merge that needs testing?  Are the proxies and ports all working?  By this I am not referring to WebCP although Webcp makes a good testing platform for that question to be answered.

**Comment by l-arnold** [comment]
Sorry to have multiple "issues" in some comments.  Seemed to be following threads rather than "issue" structure.

RE Updating Conf's.  Has that merge been tested?  Something I can look at.  I saw some merge requests from Jeremy but need to know, on my side, how to look at the effect (in action).  Would assume I would aim at @JedMeister Branch if it has not been merged.  Wondering if it includeds the HotFix updates from @DocCyblade  yesterday.

**Comment by DocCyblade** [comment]
Merged - Test with branch dev-beta-5

**Comment by JedMeister** [comment]
THis should perhaps be reopened...? Just realised I made a mistake... See https://github.com/DocCyblade/tkl-odoo/pull/31

**Comment by DocCyblade** [comment]
I'll close this once I do a test build

**Comment by DocCyblade** [comment]
Test build good. Closing this
