### ISSUE TITLE
bug - error /longpolling/poll

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#40]
Error in logs

**Comment by DocCyblade** [comment]
Need to confirm this, I saw this only once in the log file. Need someone else to see if it's a real error or just a warning. Also need to know what this even means in the context of Odoo

**Comment by JedMeister** [comment]
Had a quick look online and it seems that this is only an issue when workers are used. [This comment](https://github.com/odoo/odoo/issues/3793#issuecomment-63941914) (and the Apache conf example in a comment below) look like the go! Although it is using Nginx rather than Apache; [this](http://stackoverflow.com/questions/30161575/odoo-on-debian-longpolling-port-is-never-used-opened) may suggest why you have not seen this error more (and suggests another likely dependency)?

**Comment by DocCyblade** [comment]
@l-arnold - It seems this is needed for the live chat and gevent process (workers=2)
https://www.odoo.com/documentation/master/setup/deploy.html#livechat

I found the issue and made changes on a live system and the errors went away! 

I made the changes and push them to the dev-rc1

**Comment by DocCyblade** [comment]
This looks good, no errors in log files
